# Generated by Django 4.2 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55)),
                ('lastname', models.CharField(max_length=55)),
                ('dob', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('district', models.CharField(max_length=55)),
                ('town', models.CharField(max_length=55)),
                ('zipcode', models.CharField(max_length=55)),
                ('phonenumber1', models.CharField(max_length=55)),
                ('phonenumber2', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
    ]
